function calcularLetra (dni) {
    
    console.log(dni);

}

calcularLetra();

//* UNA VARIABLE LA UTILIZARÉ EN MI DÍA A DÍA PARA GUARDAR DATOS, GUARDAR VALORES Y MODIFICARLOS SI ASÍ LO DESEO O CONSULTARLOS

//! UNA FUNCIÓN LA UTILIZARÉ EN MI DÍA A DÍA COMO UNA CAJA DONDE GUARDO UNA FUNCIONALIDAD DE MI PÁGINA