export const characters = [
  {
    nombre: "María",
    imagen: "/assets/Maria.jpeg",
    colorDePelo: "castaño",
    sexo: "mujer",
    gafas: true,
    complementoEnLaCabeza: "diadema",
    pelo: "largo",
    belloFacial: false,
    longitudDelPelo: "largo",
    vivo: true,
    tez: "clara",
  },
  {
    nombre: "Juan",
    imagen: "/assets/Juan.jpeg",
    colorDePelo: "negro",
    sexo: "hombre",
    gafas: true,
    complementoEnLaCabeza: "gorra",
    pelo: "corto",
    belloFacial: true,
    longitudDelPelo: "corto",
    tez: "clara",
    vivo: true,
  },
  {
    nombre: "Sofía",
    imagen: "/assets/Sofia.jpeg",
    colorDePelo: "rubio",
    sexo: "mujer",
    gafas: false,
    complementoEnLaCabeza: "sombrero",
    pelo: "medio",
    belloFacial: false,
    longitudDelPelo: "medio",
    tez: "pálida",
    vivo: true,
  },
];

export const charactersCopy = [
  {
    nombre: "María",
    imagen: "/assets/Maria.jpeg",
    colorDePelo: "castaño",
    sexo: "mujer",
    gafas: true,
    complementoEnLaCabeza: "diadema",
    pelo: "largo",
    belloFacial: false,
    longitudDelPelo: "largo",
    vivo: true,
    tez: "clara",
  },
  {
    nombre: "Juan",
    imagen: "/assets/Juan.jpeg",
    colorDePelo: "negro",
    sexo: "hombre",
    gafas: true,
    complementoEnLaCabeza: "gorra",
    pelo: "corto",
    belloFacial: true,
    longitudDelPelo: "corto",
    tez: "clara",
    vivo: true,
  },
  {
    nombre: "Sofía",
    imagen: "/assets/Sofia.jpeg",
    colorDePelo: "rubio",
    sexo: "mujer",
    gafas: false,
    complementoEnLaCabeza: "sombrero",
    pelo: "medio",
    belloFacial: false,
    longitudDelPelo: "medio",
    tez: "pálida",
    vivo: true,
  },
];
