export const imgTipos = {
  grass: "/assets/tipos/grass.svg",
  fire: "/assets/tipos/fire.svg",
  water: "/assets/tipos/water.svg",
  rock: "/assets/tipos/rock.svg",
  poison: "/assets/tipos/poison.svg",
  electric: "/assets/tipos/electric.svg",
  ice: "/assets/tipos/ice.svg",
  flying: "/assets/tipos/flying.svg",
  bug: "/assets/tipos/bug.svg",
  normal: "/assets/tipos/normal.svg",
  ground: "/assets/tipos/ground.svg",
  fairy: "/assets/tipos/fairy.svg",
  fighting: "/assets/tipos/fighting.svg",
  psychic: "/assets/tipos/psychic.svg",
  steel: "/assets/tipos/steel.svg",
  ghost: "/assets/tipos/ghost.svg",
  dragon: "/assets/tipos/dragon.svg",
};